name: smart_ad_ABtesting
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1s
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python mlflow_train.py
